---
# tasks file for roles/jenkins

- name: Get jenkins apt key
  become: true
  ansible.builtin.apt_key:
    url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
    state: present

- name: Ensure the repository is configured
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install OpenJDK
  become: true
  ansible.builtin.apt:
    name: openjdk-11-jre
    state: present

- name: Install jenkins
  become: true
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Start Jenkins as a service
  become: true
  ansible.builtin.service:
    name: jenkins
    enabled: true
    state: started