- hosts: jenkins_controller
  become: true
  vars: {
    jenkins_ssh_dir: /var/lib/jenkins/.ssh
  }
  tasks:
    - name: Create Jenkins SSH dir
      ansible.builtin.file:
        path: '{{ jenkins_ssh_dir }}'
        state: directory

    - name: Recognize maven builder as known host
      ansible.builtin.shell:
        cmd: 'ssh-keyscan {{ hostvars["maven"].ansible_host }} > {{ jenkins_ssh_dir }}/known_hosts'

    - name: Recognize dotnet builder as known host
      ansible.builtin.shell:
        cmd: 'ssh-keyscan {{ hostvars["dotnet"].ansible_host }} >> {{ jenkins_ssh_dir }}/known_hosts'

    - name: Give Jenkins ownership over .ssh
      ansible.builtin.shell:
        cmd: 'chown -R jenkins {{ jenkins_ssh_dir }}'