- hosts: jenkins_controller
  become: true
  vars: {
    jenkins_ssh_dir: '/var/lib/jenkins/.ssh'
  }
  tasks:
    - name: Get jenkins apt key
      ansible.builtin.apt_key:
        url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
        state: present
    
    - name: Ensure the repository is configured
      ansible.builtin.apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-11-jre
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: latest

    - name: Start Jenkins as a service
      ansible.builtin.service:
        name: jenkins
        enabled: true
        state: started

    - name: Create Jenkins SSH dir
      ansible.builtin.file:
        path: '{{ jenkins_ssh_dir }}'
        state: directory

    - name: Recognize maven builder as known host
      ansible.builtin.shell:
        cmd: 'runuser -u jenkins -- ssh-keyscan {{ hostvars["maven"].ansible_host }} >> {{ jenkins_ssh_dir }}/known_hosts'

    - name: Recognize dotnet builder as known host
      ansible.builtin.shell:
        cmd: 'runuser -u jenkins -- ssh-keyscan {{ hostvars["dotnet"].ansible_host }} >> {{ jenkins_ssh_dir }}/known_hosts'