Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.network "public_network", bridge: "enps0s0", ip: "192.168.0.21"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "nexus"
        vb.memory = "4096"
    end

    config.vm.provision "shell", path: "vagrant_setup_nexus.sh"

end

Vagrant.configure.("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.network "public_network", bridge: "enps0s0", ip: "192.168.0.22"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "gitlab"
        vb.memory = "4096"
    end

    config.vm.provision "shell", path: "vagrant_setup_gitlab.sh"

end