Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.define "nexus" do |nexus|

        nexus.vm.network "public_network", bridge: "enps0s0", ip: "192.168.0.21"

        nexus.vm.provider "virtualbox" do |vb|
            vb.name = "nexus"
            vb.memory = "4096"
        end

        nexus.vm.provision "shell", path: "vagrant_setup_nexus.sh"
    end

    config.vm.define "gitlab" do |gitlab|

        gitlab.vm.network "public_network", bridge: "enps0s0", ip: "192.168.0.22"

        gitlab.vm.provider "virtualbox" do |vb|
            vb.name = "gitlab"
            vb.memory = "4096"
        end

        gitlab.vm.provision "shell", path: "vagrant_setup_gitlab.sh"
    end
    
end