- hosts: jenkins
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
    
    - name: Run Jenkins container
      ansible.builtin.shell:
        cmd: "docker run -d -p 7000:8080 -v jenkins_data:/var/jenkins_home jenkins/jenkins:lts-jdk11"
        