Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.network "public_network", bridge: "enp30s0", ip: "192.168.0.32"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "gitlab_runner"
    end

    config.vm.provision "shell", path: "setup_mvn_gitlab_runner.sh"

end