Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.network "public_network", bridge: "wls1", ip: "192.168.0.31"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jenkins_builder"
    end

    config.vm.provision "shell", path: "setup_mvn_jenkins_builder.sh"

end