Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox"
    config.vm.box = "ubuntu/focal64"

    config.vm.network "public_network", bridge: "wls1", ip: "192.168.0.31"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "jenkins_builder"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y openjdk-11-jre maven
        
        useradd -m -s /bin/bash jenkins
        echo -ne "jenkins\njenkins" | passwd jenkins

        sed -i 's/^PasswordAuthentication no/#&/' /etc/ssh/sshd_config
        systemctl restart sshd.service
    SHELL

end